spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/webdb
    username: webuser
    password: webuser
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
